import createClient from "openapi-fetch";
import { createQueryHook } from "swr-openapi";
import type { paths } from "../../openapi"; // generated by openapi-typescript

export const backend = process.env.NODE_ENV === "production" ? "" : "http://localhost:8000"

export const fetcher: typeof fetch = (input, ...args) => fetch(backend + input, ...args).then(res => res.json())

const client = createClient<paths>({
    baseUrl: backend,
});

export const useQuery = createQueryHook(client, "my-api");